version: "3.2"
services:
#command: -server -advertise HOSTIP -bootstrap
#
#  zdiscord:
#    image: dd01d599ca9e
#    tty: true
#  nginx:
#    image: ingress
#    ports:
#      - "0.0.0.0:80:80"
#  minio:
#    image: minio
#    container_name: minio
#    ports:
#     - "0.0.0.0:8888:8888"
#    volumes:
#    - /Users/zach.mcfadden/Documents/projects/side_stuff/zservers:/mnt/mount/something
#    tty: true

  vault:
    image: zvault
    container_name: vault
    cap_add:
      - IPC_LOCK
    ports:
      - "0.0.0.0:8200:8200"
      - "0.0.0.0:8080:8080"
    environment:
      VAULT_DEV_LISTEN_ADDRESS: '0.0.0.0:8200'
      SERVICE_DISCOVERY: 'servicediscovery:2181'
      VAULT_ADDR: '0.0.0.0:8200'
      SECRET_JSON_STR: '{"discord":[{"key":"apiKey","value":"somekey"}]}'

#  elasticsearch:
#    image: es
#    container_name: elasticsearch
#    ports:
#      - "0.0.0.0:9200:9200"
#
#  kibana:
#    image: kib
#    container_name: kibana
#    ports:
#      - "0.0.0.0:5601:5601"

  servicediscovery:
    image: servicediscovery
    restart: always
    container_name: servicediscovery
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181

  web:
    image: elkozmon/zoonavigator-web:latest
    container_name: zoonavigator-web
    ports:
     - "9001:9001"
    environment:
      API_HOST: "api"
      API_PORT: 9000
      WEB_HTTP_PORT: 9001
    depends_on:
     - api
    restart: always
  api:
    image: elkozmon/zoonavigator-api:latest
    container_name: zoonavigator-api
    environment:
      SERVER_HTTP_PORT: 9000
    depends_on:
     - servicediscovery
    restart: always
