version: "3.2"
services:
#command: -server -advertise HOSTIP -bootstrap
#
#  zdiscord:
#    image: dd01d599ca9e
#    tty: true
#  nginx:
#    image: ingress
#    ports:
#      - "0.0.0.0:80:80"
  minio:
    image: minio
    container_name: minio
    ports:
     - "0.0.0.0:8888:8888"
    volumes:
    - /Users/zach.mcfadden/Documents/projects/side_stuff/zservers:/mnt/mount/something
    tty: true
  vault:
    image: vault
    container_name: vault
    cap_add:
      - IPC_LOCK
    ports:
      - "0.0.0.0:8200:8200"
      - "0.0.0.0:8080:8080"
  elasticsearch:
    image: es
    container_name: elasticsearch
    ports:
      - "0.0.0.0:9200:9200"
  kibana:
    image: kib
    container_name: kibana
    ports:
      - "0.0.0.0:5601:5601"
