#! /bin/sh

# Auto generated by steps/000env.sh
source env.sh

nohup vault server -dev -dev-listen-address=0.0.0.0:8200 -dev-root-token-id=$DISPATCHER_AUTH_TOKEN -config vault-server.hcl >/dev/stdout 2>&1 &

sleep 6
vault token create --format json > token.json

# Generate Secrets 
vault secrets enable kv-v2
vault secrets enable -path=secrets kv

./dispatcher/run.sh $DISPATCHER_AUTH_TOKEN token.json $VAULT_ADDR